const langDict = {
    en: {
        atLeastOneDatePair: 'You must have at least one date pair.',
        calculate: 'Calculate',
        checkMonths: 'Please check your months. (YYYYMM)',
        checkYears: 'Please check your years. (YYYYMM)',
        contribDict: {
            Ghost: 'Ghost',
            Low: 'Low',
            Medium: 'Medium',
            High: 'High',
        },
        defaultResponseText: {
            techStack: 'No stack found',
            expertLanguages: 'No languages found',
            githubActivity: 'No GitHub activity found',
            expertise: 'No expertise found',
            yearsActive: 'No years active found',
            profileLink: 'No profile link found',
        },
        emptyDate: 'Please fill out all date inputs.',
        endDateBeforeStartDate: 'Start date must be before end date.',
        enterUsername: 'Please enter a username.',
        experiences: 'Experiences',
        expertDict: {
            Newbie: 'Newbie',
            Junior: 'Junior',
            Senior: 'Senior',
        },
        expertiseText: 'Expertise',
        expertLanguages: 'Expert Languages',
        githubActivity: 'GitHub Activity',
        githubProfileLink: 'GitHub Profile Link',
        headerText: 'DevScouter',
        invalidDate: 'Please enter a valid date. (YYYYMM)',
        month: 'month(s)',
        search: 'Search',
        serverIsWrong: 'Something went wrong with the server. Please try again later.',
        somethingIsWrong: 'An error occurred. Please try again later.',
        stackDict: {
            Backend: 'Backend',
            Frontend: 'Frontend',
            Fullstack: 'Fullstack',
        },
        subText: 'GitHub Dev Search',
        techStack: 'Tech Stack',
        totalExperience: 'Total Experience',
        userDoesNotExist: 'User does not exist. Check the spelling and try again.',
        username: 'Username',
        year: 'year(s)',
        yearsActive: 'Years Active',
        yearsOfExperience: 'Years of Experience',
    },
    kr: {
        atLeastOneDatePair: '최소한 하나의 날짜 쌍이 필요합니다.',
        calculate: '계산하기',
        checkMonths: '개월을 확인해주세요. (YYYYMM)',
        checkYears: '년도를 확인해주세요. (YYYYMM)',
        contribDict: {
            Ghost: '유령회원',
            Low: '낮음',
            Medium: '중간',
            High: '높음',
        },
        defaultResponseText: {
            techStack: '기술 스택이 없습니다.',
            expertLanguages: '전문 언어가 없습니다.',
            githubActivity: '깃허브 활동이 없습니다.',
            expertise: '전문성이 없습니다.',
            yearsActive: '활동년수가 없습니다.',
            profileLink: '프로필 링크가 없습니다.',
        },
        emptyDate: '날짜를 입력해주세요.',
        endDateBeforeStartDate: '시작 날짜는 종료 날짜보다 빨라야 합니다.',
        enterUsername: '유저네임을 입력해주세요.',
        experiences: '경력',
        expertDict: {
            Newbie: '뉴비',
            Junior: '주니어',
            Senior: '시니어',
        },
        expertiseText: '전문성',
        expertLanguages: '전문 언어',
        githubActivity: '깃허브 활동',
        githubProfileLink: '깃허브 프로필 링크',
        headerText: '데브스카우터',
        invalidDate: '올바른 날짜를 입력해주세요. (YYYYMM)',
        month: '개월',
        search: '검색하기',
        serverIsWrong: '서버에 문제가 발생했습니다. 나중에 다시 시도해주세요.',
        somethingIsWrong: '에러가 발생했습니다. 나중에 다시 시도해주세요.',
        stackDict: {
            Backend: '백엔드',
            Frontend: '프론트엔드',
            Fullstack: '풀스택',
        },
        subText: '한눈에 보는 개발자',
        techStack: '기술 스택',
        totalExperience: '총 경력',
        userDoesNotExist: '유저가 존재하지 않습니다. 철자를 확인하고 다시 시도해주세요.',
        username: '깃허브 유저네임',
        year: '년',
        yearsActive: '활동년수',
        yearsOfExperience: '경력 계산기',
    }
};

export default langDict;
