const langDict = {
    en: {
        atLeastOneDatePair: 'You must have at least one date pair.',
        checkMonths: 'Please check your months. (YYYYMM)',
        checkYears: 'Please check your years. (YYYYMM)',
        emptyDate: 'Please fill out all date inputs.',
        endDateBeforeStartDate: 'Start date must be before end date.',
        enterUsername: 'Please enter a username.',
        experiences: 'Experiences',
        expertise: 'Expertise',
        expertLanguages: 'Expert Languages',
        githubActivity: 'GitHub Activity',
        githubProfileLink: 'GitHub Profile Link',
        headerText: 'DevScouter - GitHub Dev Search',
        invalidDate: 'Please enter a valid date. (YYYYMM)',
        serverIsWrong: 'Something went wrong with the server. Please try again later.',
        somethingIsWrong: 'An error occurred. Please try again later.',
        submit: 'Submit',
        techStack: 'Tech Stack',
        totalExperience: 'Total Experience',
        userDoesNotExist: 'User does not exist. Check the spelling and try again.',
        username: 'Username',
        yearsActive: 'Years Active',
        yearsOfExperience: 'Years of Experience',
    },
    kr: {
        atLeastOneDatePair: '최소한 하나의 날짜 쌍이 필요합니다.',
        checkMonths: '개월을 확인해주세요. (YYYYMM)',
        checkYears: '년도를 확인해주세요. (YYYYMM)',
        emptyDate: '날짜를 입력해주세요.',
        endDateBeforeStartDate: '시작 날짜는 종료 날짜보다 빨라야 합니다.',
        enterUsername: '유저네임을 입력해주세요.',
        experiences: '경력',
        expertise: '전문성',
        expertLanguages: '전문 언어',
        githubActivity: '깃허브 활동',
        githubProfileLink: '깃허브 프로필 링크',
        headerText: '데브스카우터 - 한눈에 보는 개발자',
        invalidDate: '올바른 날짜를 입력해주세요. (YYYYMM)',
        serverIsWrong: '서버에 문제가 발생했습니다. 나중에 다시 시도해주세요.',
        somethingIsWrong: '에러가 발생했습니다. 나중에 다시 시도해주세요.',
        submit: '제출',
        techStack: '기술 스택',
        totalExperience: '총 경력',
        userDoesNotExist: '유저가 존재하지 않습니다. 철자를 확인하고 다시 시도해주세요.',
        username: '유저네임',
        yearsActive: '활동년수',
        yearsOfExperience: '경력 계산기',
    }
};

export default langDict;
